task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0-snap
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --notest Expect
    - cpanm --installdeps .
    - perl makefile-expect-driver.pl FreeBSD Unix OSFeatures::POSIXShellRedirection HWCapabilities::Int64
    - make
    - make test

task:
  name: MacOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-ventura-base:latest
  test_script:
    - echo|cpan App::cpanminus
    - /Users/admin/perl5/bin/cpanm -v --no-interactive IO::Tty
    - /Users/admin/perl5/bin/cpanm --notest Expect
    - /Users/admin/perl5/bin/cpanm --installdeps .
    - perl makefile-expect-driver.pl Unix OSFeatures::POSIXShellRedirection Apple MacOSX MacOSX::v13 HWCapabilities::Int64
    - export PERL5LIB=/Users/admin/perl5/lib/perl5
    - make
    - make test
