freebsd_instance:
  image: freebsd-12-0-release-amd64

freebsd_tests_task:
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --notest Expect
    - cpanm --installdeps .
    - perl makefile-expect-driver.pl FreeBSD Unix OSFeatures::POSIXShellRedirection
    - make
    - make test
