task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0-snap
  test_script:
    - pkg install -y perl5
    - echo|cpan App::cpanminus
    - cpanm --notest Expect
    - cpanm --installdeps .
    - perl makefile-expect-driver.pl FreeBSD Unix OSFeatures::POSIXShellRedirection
    - make
    - make test

task:
  name: MacOS
  osx_instance:
    image: catalina-xcode-12.0
  test_script:
    - echo|cpan App::cpanminus
    - perl -MExtUtils::Makemaker -E 'if($ExtUtils::Makemaker::VERSION < 7.50) { exec("/Users/anka/perl5/bin/cpanm http://cpan.mirrors.hoobly.com/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.49_04.tar.gz") }'
    - /Users/anka/perl5/bin/cpanm -v --no-interactive IO::Tty
    - /Users/anka/perl5/bin/cpanm --notest Expect
    - /Users/anka/perl5/bin/cpanm --installdeps .
    - perl makefile-expect-driver.pl Unix OSFeatures::POSIXShellRedirection Apple MacOSX MacOSX::v10_15
    - make
    - make test
