language: perl
dist: trusty
env: PERL_USE_UNSAFE_INC=0
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
script:
  - cpanm Expect && perl makefile-expect-driver.pl Linux Unix OSFeatures::POSIXShellRedirection && make test
matrix:
  include:
    - perl: "5.20"
      env: COVERAGE=1
  allow_failures:
    - perl: blead
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
sudo: false
