name: Alpine Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine
    steps:
    - uses: actions/checkout@v4
    - name: Test on Alpine
      run: |
        cat /etc/os-release
        apk add perl gcc make git
        yes|perl -MCPAN -e 'install qw(App::cpanminus local::lib Expect)'
        export PERL5OPT=-Mlocal::lib
        /usr/local/bin/cpanm --installdeps .
        perl makefile-expect-driver.pl Linux Unix OSFeatures::POSIXShellRedirection HWCapabilities::Int64 Linux::Alpine
        make test
