name: Devuan Linux
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devuan/devuan:latest
    steps:
    - uses: actions/checkout@v4
    - name: Test on Devuan
      run: |
        cat /etc/os-release
        apt-get update
        yes|apt-get install perl-base build-essential make gcc lsb-release
        yes|perl -MCPAN -e 'install App::cpanminus'
        yes|perl -MCPAN -e 'install local::lib'
        yes|perl -MCPAN -e 'install Expect'
        export PERL5OPT=-Mlocal::lib
        /usr/local/bin/cpanm --installdeps .
        perl makefile-expect-driver.pl Linux::Debian Linux::Devuan Linux Unix OSFeatures::POSIXShellRedirection HWCapabilities::Int64
        make test
