name: Arch Linux
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devuan:latest
    steps:
    - uses: actions/checkout@v2
    - name: Test on Devuan
      run: |
        cat /etc/os-release
        sudo apt-get install perl build-essential
        yes|perl -MCPAN -e 'install App::cpanminus'
        yes|perl -MCPAN -e 'install local::lib'
        export PERL5OPT=-Mlocal::lib
        /usr/bin/site_perl/cpanm --installdeps .
        perl Makefile.PL
        make test
