on: [push, pull_request]
name: Linux

jobs:
  list:
    name: list available perl versions
    runs-on: 'ubuntu-latest'
    steps:
      - uses: shogo82148/actions-setup-perl@v1
      - id: set-matrix
        name: list available perl versions
        shell: perl {0}
        run: |
          use Actions::Core;
          set_output(matrix => {perl => [perl_versions()]});
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  build:
    runs-on: 'ubuntu-latest'
    needs: list
    strategy:
      matrix: ${{fromJson(needs.list.outputs.matrix)}}
    name: Perl ${{ matrix.perl }}
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: switch to perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - name: run tests
        env:
          PERL_USE_UNSAFE_INC: 0
        run: |
            perl -v
            cpanm Expect ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage || cat /home/runner/.cpanm/work/*/build.log
            perl -Mparent -e0 || cpanm parent
            rm -rf /home/runner/.cpanm/work/*
            cpanm --installdeps . || cat /home/runner/.cpanm/work/*/build.log
            perl makefile-expect-driver.pl Linux::Debian Linux::Ubuntu Linux Unix OSFeatures::POSIXShellRedirection
            make test TEST_VERBOSE=1
