name: Real Debian Linux
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    steps:
    - uses: actions/checkout@v4
    - name: Test on real Debian
      run: |
        cat /etc/os-release
        mkdir -p /run/systemd/system
        apt-get update
        yes|apt-get install perl-base build-essential make gcc lsb-release
        lsb_release -i
        yes|perl -MCPAN -e 'install App::cpanminus'
        yes|perl -MCPAN -e 'install local::lib'
        yes|perl -MCPAN -e 'install Expect'
        export PERL5OPT=-Mlocal::lib
        /usr/local/bin/cpanm --installdeps .
        perl makefile-expect-driver.pl Linux::Debian Linux::RealDebian Linux Unix OSFeatures::Systemd OSFeatures::POSIXShellRedirection HWCapabilities::Int64
        make test
