---
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        distribution: strawberry
        perl-version: ${{ matrix.perl-version }}
    - name: perl -V
      run: perl -V
    - name: Install Dependencies
      run: |
        cpanm ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage || cat $HOME/.cpanm/work/*/build.log
        cpanm --installdeps . || cat $HOME/.cpanm/work/*/build.log
    - name: Run Tests
      run: |
        perl Makefile.PL
        if( "${{ matrix.perl-version }}" -lt "5.26" ) { dmake test TEST_VERBOSE=1 } else { gmake test TEST_VERBOSE=1 }
    strategy:
      fail-fast: false
      matrix:
        perl-version:
        - '5.20'
        - '5.22'
        - '5.24'
        - '5.26'
        - '5.28'
        - '5.30'
        - '5.32'
        - latest
name: Windows
on:
- push
- pull_request
