# cribbed from https://stackoverflow.com/questions/72367353/testing-perl-on-windows-with-github-actions

on: [push, pull_request]
name: Windows

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'
          - '5.32'
          - '5.34'
          - 'latest'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          cpanm ExtUtils::MakeMaker Test::Pod Test::Pod::Coverage || cat $HOME/.cpanm/work/*/build.log
          cpanm --installdeps . || cat $HOME/.cpanm/work/*/build.log
      - name: Run Tests
        run: |
          perl Makefile.PL
          make test TEST_VERBOSE=1

